import { useMemo, useState } from 'react'
import { ChevronRight, Clock3, FileText, Search, ShieldCheck, Users, X } from 'lucide-react'
import { type Script } from './api'
import { CaseCard } from './Layout'
import { npcAvatar } from './media/npc-avatars'
import { coverImages } from './media/covers'

export default function Library({scripts,selected,onOpen,onClose,start,busy}:{scripts:Script[];selected:Script|null;onOpen:(s:Script)=>void;onClose:()=>void;start:(config:{difficulty:string;perspective:string;partner_style:string})=>void;busy:boolean}){
 const [genre,setGenre]=useState('全部'),[query,setQuery]=useState(''),[difficulty,setDifficulty]=useState('全部'),[duration,setDuration]=useState('全部')
 const [mode,setMode]=useState('standard'),[perspective,setPerspective]=useState('侦探'),[partner,setPartner]=useState('逻辑')
 const filtered=useMemo(()=>scripts.filter(s=>(genre==='全部'||s.genre===genre)&&(difficulty==='全部'||s.difficulty===difficulty)&&(duration==='全部'||s.duration<=Number(duration))&&[s.title,s.description,...s.tags].join(' ').includes(query)),[scripts,genre,query,difficulty,duration])
 return <div className="page library-page"><div className="library-head"><div><span className="section-kicker">CASE ARCHIVE / 预设内容</span><h1>剧本库</h1><p>三起独立案件，三种解开真相的方式。选择一个案件，进入专属于你的调查现场。</p></div><div className="filter-pills">{['全部',...new Set(scripts.map(s=>s.genre))].map(g=><button key={g} className={`pill ${g===genre?'active':''}`} onClick={()=>setGenre(g)}>{g}</button>)}</div><div className="library-filters"><label className="search-field"><Search size={15}/><input aria-label="搜索剧本" placeholder="搜索案件、线索主题…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="筛选难度" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>全部</option>{['入门','进阶','烧脑'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="筛选时长" value={duration} onChange={e=>setDuration(e.target.value)}><option value="全部">不限时长</option><option value="40">40 分钟以内</option><option value="60">60 分钟以内</option></select></div></div>
 {selected&&<div className="script-drawer" role="region" aria-label="剧本详情"><div className={'cover cover-'+selected.cover+' drawer-cover '+(coverImages[selected.cover]?'cover-has-image':'')} style={coverImages[selected.cover]?{backgroundImage:`url(${coverImages[selected.cover]})`}:undefined}><span className="cover-genre">{selected.genre}</span><div className="cover-title"><small>{selected.subtitle}</small><strong>{selected.title}</strong></div></div><div className="drawer-body"><button className="close-drawer" aria-label="关闭剧本详情" onClick={onClose}><X size={17}/></button><span className="section-kicker">CASE FILE / V{selected.version}.0</span><h2>{selected.title}</h2><p className="drawer-intro">{selected.intro||selected.description}</p><div className="drawer-facts"><span><Users size={16}/>{selected.character_count} 位角色</span><span><FileText size={16}/>{selected.evidence_count} 件证物</span><span><Clock3 size={16}/>{selected.duration} 分钟</span></div><div className="drawer-people">{selected.characters?.map(c=>{const avatar=npcAvatar(selected.id,c.id);return <div key={c.id} className="mini-person"><span style={{background:c.color}}>{avatar?<img src={avatar} alt={`${c.name}头像`}/>:c.name[0]}</span><small>{c.name}<br/><b>{c.role}</b></small></div>})}</div><div className="start-config"><label>调查模式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="story">故事 · 充裕调查点</option><option value="standard">标准 · 60 调查点</option><option value="expert">挑战 · 40 调查点</option></select></label><label>身份视角<select value={perspective} onChange={e=>setPerspective(e.target.value)}>{['侦探','记者','法医'].map(x=><option key={x}>{x}</option>)}</select></label><label>搭档风格<select value={partner} onChange={e=>setPartner(e.target.value)}>{['逻辑','质疑','陪伴','法证'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="warning-row"><ShieldCheck size={15}/>内容提示：{selected.warnings.join(' · ')}</div><button className="primary-button wide" disabled={busy} onClick={()=>start({difficulty:mode,perspective,partner_style:partner})}>{busy?'正在开封…':'打开卷宗'}<ChevronRight size={16}/></button></div></div>}
 <div className="library-grid" style={{marginTop:24}}>{filtered.map(s=><CaseCard key={s.id} script={s} index={scripts.findIndex(x=>x.id===s.id)} onClick={()=>onOpen(s)}/>)}</div>{!filtered.length&&<div className="empty-state">没有符合条件的卷宗。试着调整筛选条件。</div>}</div>
}

