import { useCallback, useEffect, useRef, useState } from 'react'
import { BrainCircuit, ChevronRight, Clock3, Eye, FileText, FlaskConical, Lightbulb, MapPin, MessageCircle, NotebookPen, Search, Send, ShieldCheck, Sparkles, Square, Target, WifiOff, Zap } from 'lucide-react'
import { ApiError, api, command, formatDate, idem, localDB, type Evidence, type GameState, type Note, type User } from './api'
import { Reveal } from './Reveal'
import EvidencePanel from './EvidencePanel'
import NotesPanel from './NotesPanel'
import Submission from './Submission'

const statusLabel:Record<string,string>={queued:'正在排队',generating:'正在组织回应',reviewing:'正在检查披露权限',revising:'正在修订回应',approved:'回应已通过审核',delivering:'正在交付证词',failed:'本轮回答未完成',cancelled:'回答已停止',expired:'服务已重启，请重试'}
export default function PlayScript({state,setState,user,notice,setPage,refreshHistory,showHistory}:{state:GameState;setState:(x:GameState)=>void;user:User;notice:(x:string)=>void;setPage:(x:string)=>void;refreshHistory:()=>Promise<void>;showHistory:boolean}){
 const [tab,setTab]=useState('scene'),[actor,setActor]=useState(state.characters[0]?.id||''),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false)
 const [online,setOnline]=useState(navigator.onLine),[runStatus,setRunStatus]=useState(''),[failedQuestion,setFailedQuestion]=useState(''),[search,setSearch]=useState('')
 const [incoming,setIncoming]=useState<Note|null>(null),[settle,setSettle]=useState(false),[level,setLevel]=useState(2),[pending,setPending]=useState<any[]>([])
 const currentRef=useRef(state),streamRefresh=useRef(false),actionLock=useRef(false)
 currentRef.current=state
 const refresh=useCallback(async()=>{const s:GameState=await api(`/api/v1/sessions/${state.id}/state`);setState(s)},[state.id,setState])
 const loadPending=useCallback(async()=>{setPending((await localDB.intents.where('sessionId').equals(state.id).toArray()).filter(x=>x.userId===user.id))},[state.id,user.id])
 useEffect(()=>{loadPending();const on=()=>{setOnline(true);refresh().catch(()=>{})},off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[loadPending,refresh])
 useEffect(()=>{
  if(!state.active_run)return
  const rid=state.active_run;let disposed=false;let es:EventSource|null=null;let latest=0;let done=false
  const update=async()=>{if(streamRefresh.current||disposed)return;streamRefresh.current=true;try{await refresh()}catch{}finally{streamRefresh.current=false}}
  const consume=(event:any)=>{if(disposed||event.seq<=latest)return;latest=event.seq;if(event.type==='run.status')setRunStatus(event.status)
   if(event.type==='message.chunk')update()
   if(['run.completed','run.failed','run.cancelled','run.expired'].includes(event.type)){done=true;setRunStatus(event.status||'completed');es?.close();update();if(event.type==='run.failed'||event.type==='run.expired'){api(`/api/v1/runs/${rid}`).then(r=>{if(!disposed)setFailedQuestion(r.question)}).catch(()=>{});notice(event.code==='BUDGET_EXCEEDED'?'模型调用额度已用完，可切换本地演示。':'这轮回应未交付完成，已保留收到的证词。你可以重试。')}}
  }
  es=new EventSource(`/api/v1/runs/${rid}/events?after=0`)
  for(const type of ['run.status','message.chunk','run.completed','run.failed','run.cancelled','run.expired'])es.addEventListener(type,(e)=>{try{consume(JSON.parse((e as MessageEvent).data))}catch{}})
  es.onerror=()=>{if(done)es?.close()}
  // Durable REST polling also recovers when proxies or background tabs interrupt SSE.
  const fallback=setInterval(async()=>{if(disposed||done||!navigator.onLine)return;try{const r=await api(`/api/v1/runs/${rid}`);for(const e of r.events)consume(e);if(['completed','failed','cancelled','expired'].includes(r.status)){done=true;update()}}catch{}},1800)
  return()=>{disposed=true;es?.close();clearInterval(fallback)}
 },[state.active_run,state.id,refresh,notice])
 const action=async(body:any)=>{
  if(actionLock.current)return
  const current=currentRef.current,key=idem(),request={...body,expected_version:current.version}
  await localDB.intents.put({key,userId:user.id,sessionId:state.id,body:request,expected:current.version,status:navigator.onLine?'sending':'queued'})
  if(!navigator.onLine){notice('调查意图已保存在本机；联网后核验，暂不发放证物。');await loadPending();return}
  actionLock.current=true;setBusy(true)
  try{const d=await command(`/api/v1/sessions/${state.id}/actions`,request,key);setState(d.state);notice(d.message);await localDB.intents.delete(key)}catch(e:any){if(e instanceof ApiError){await localDB.intents.delete(key);if(e.status===409)await refresh().catch(()=>{});notice(e.message)}else{notice('连接中断。这次操作已排队，可联网后重试核验。')}}finally{actionLock.current=false;setBusy(false);await loadPending()}
 }
 const syncPending=async()=>{if(actionLock.current)return;actionLock.current=true;setBusy(true);try{for(const intent of pending){const latest:GameState=await api(`/api/v1/sessions/${state.id}/state`);const request=intent.status==='queued'?{...intent.body,expected_version:latest.version}:intent.body;await localDB.intents.update(intent.key,{body:request,status:'sending'});try{const d=await command(`/api/v1/sessions/${state.id}/actions`,request,intent.key);setState(d.state);await localDB.intents.delete(intent.key)}catch(e:any){if(e instanceof ApiError){await localDB.intents.update(intent.key,{status:'conflict'});notice(e.message+' 未执行的意图仍保留，可取消后重新选择。')}else throw e}}}catch(e:any){notice(e.message||'网络仍不可用')}finally{actionLock.current=false;setBusy(false);loadPending()}}
 const ask=async(retry?:string)=>{const text=(retry||question).trim();if(!text||actionLock.current||state.active_run)return;actionLock.current=true;setBusy(true);setFailedQuestion('');try{const d=await command(`/api/v1/sessions/${state.id}/dialogue-runs`,{expected_version:currentRef.current.version,actor_id:actor,question:text});setState(d.state);setQuestion('');setRunStatus('queued')}catch(e:any){notice(e.message);if(e instanceof ApiError&&e.status===409)await refresh().catch(()=>{})}finally{actionLock.current=false;setBusy(false)}}
 const cancel=async()=>{if(!state.active_run)return;try{await api(`/api/v1/runs/${state.active_run}/cancel`,{method:'POST'});await refresh();setRunStatus('cancelled');notice('已停止。已交付的完整证词继续保存在本局。')}catch(e:any){notice(e.message)}}
 const addNote=(e:Evidence)=>{setIncoming({id:crypto.randomUUID(),version:0,kind:'fact',text:`${e.title}：${e.analyzed?e.analysis:e.description}`,source_ids:[e.id],partner_allowed:true});setTab('notes')}
 const partner=async()=>{if(busy||state.active_run)return;setBusy(true);try{const d=await command(`/api/v1/sessions/${state.id}/partner-analyses`,{expected_version:state.version,level});setState(d.state)}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 if(state.phase==='finished'&&!showHistory)return <Reveal state={state} setPage={setPage}/>
 if(settle&&state.phase!=='finished')return <Submission state={state} setState={setState} back={()=>setSettle(false)} notice={notice} onFinished={refreshHistory}/>
 const current=state.scenes.find(x=>x.id===state.current_scene)||state.scenes[0],character=state.characters.find(x=>x.id===actor)
 const closed=state.phase==='finished',blocked=busy||!!state.active_run||closed
 return <div className="page play-page">
  <div className="play-head"><div><span className="section-kicker">{closed?'ARCHIVE / 已结案调查记录':'LIVE INVESTIGATION / 正在调查'}</span><h1>{state.script.title}</h1><p>{state.script.subtitle} · {state.config.perspective}视角</p></div><div className="play-metrics"><span><Zap size={15}/>{state.config.difficulty==='story'?'∞':state.points}<small>调查点</small></span><span><Clock3 size={15}/>{state.elapsed}<small>调查分钟</small></span><span><ShieldCheck size={15}/><small>{online?'已自动保存':'离线浏览'}</small></span></div></div>
  {!online&&<div className="offline-banner"><WifiOff size={16}/>当前离线。可以编辑笔记，调查意图待联网后核验。</div>}
  {!!pending.length&&<div className="pending-banner"><b>{pending.length} 条调查意图待处理</b><button onClick={syncPending} disabled={!online||busy}>联网核验并同步</button>{pending.map(p=><button key={p.key} onClick={async()=>{await localDB.intents.delete(p.key);loadPending()}}>取消 {p.body.type}{p.status==='conflict'?'（状态冲突）':''}</button>)}</div>}
  {closed&&<button className="text-button" onClick={()=>setPage('play')}>回到结案复盘 <ChevronRight size={14}/></button>}
  <div className="play-layout"><section className="investigation-main"><div className="scene-banner"><div className="scene-banner-bg"/><div className="scene-banner-copy"><span className="scene-index">SCENE / 0{state.scenes.findIndex(x=>x.id===current.id)+1}</span><h2>{current.name}</h2><p>{current.subtitle}</p></div><MapPin size={22}/></div><div className="scene-description">{current.description}</div><div className="object-grid">{current.objects.map(o=><button key={o.id} disabled={blocked||!o.available} className={`object-card ${o.searched?'searched':''} ${!o.available?'locked':''}`} onClick={()=>action({type:'search',scene_id:current.id,object_id:o.id})}><span className="object-icon">{o.searched?'✓':o.available?'⌕':'◌'}</span><span><b>{o.name}</b><small>{o.searched?'已记录到证物栏':o.available?o.description:'先分析相关证物，再回来调查'}</small></span><ChevronRight size={16}/></button>)}</div><div className="scene-switcher">{state.scenes.map(s=><button key={s.id} className={s.id===current.id?'active':''} disabled={blocked||!s.unlocked} onClick={()=>action({type:'visit',scene_id:s.id})}><span>0{state.scenes.findIndex(x=>x.id===s.id)+1}</span>{s.name}<ChevronRight size={14}/></button>)}</div>
  <div className="dialogue-box"><div className="dialogue-header"><span><MessageCircle size={15}/>询问角色</span><span className="approved"><ShieldCheck size={13}/>证词经过核验</span></div><div className="actor-tabs">{state.characters.map(c=><button key={c.id} className={c.id===actor?'active':''} onClick={()=>setActor(c.id)}><span className="actor-avatar" style={{background:c.color}}>{c.name[0]}</span><span>{c.name}<small>{c.role}</small></span><i style={{width:`${Math.max(8,c.trust)}%`}}/></button>)}</div>{character&&<div className="actor-context"><p>{character.bio}</p><span>信任 {character.trust} · 警觉 {character.alertness} · {character.emotion}</span><button disabled={blocked} onClick={()=>action({type:'observe',actor_id:actor})}><Eye size={12}/>观察表情</button></div>}
  {!closed&&<><div className="question-suggestions">{character?.suggestions.map(s=><button key={s} onClick={()=>setQuestion(s)}>{s}</button>)}</div><div className="question-compose"><textarea aria-label="向角色提问" value={question} maxLength={1200} onChange={e=>setQuestion(e.target.value)} placeholder="输入你的问题……Enter 发送，Shift+Enter 换行" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask()}}}/><button className="send-button" aria-label="发送问题" onClick={()=>ask()} disabled={blocked||!online||!question.trim()}>{busy?<span className="spinner"/>:<Send size={17}/>}</button></div></>}
  {state.active_run&&<div className="run-progress" role="status"><span className="spinner"/>{statusLabel[runStatus]||'正在恢复回应'}<button onClick={cancel}><Square size={12}/>停止回答</button></div>}
  {!state.active_run&&failedQuestion&&<div className="run-progress"><span>本轮回应未完成</span><button onClick={()=>ask(failedQuestion)}>重试问题 · 1 调查点</button></div>}
  <label className="dialogue-search"><Search size={13}/><input aria-label="搜索对话" placeholder="搜索已保存的对话" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="message-history">{state.messages.filter(m=>m.actor_id===actor&&m.text.includes(search)).map(m=><div className={'message '+(m.role==='user'?'player-message':'')} key={m.id}><span className="message-avatar">{m.actor_name?.[0]}</span><div><small>{m.actor_name} · {formatDate(m.time)}</small><p>{m.text}</p>{m.role==='assistant'&&<button className="text-button" onClick={()=>{const s=state.statements.find(s=>s.text===m.text);setIncoming({id:crypto.randomUUID(),version:0,kind:'statement',text:`${m.actor_name}：“${m.text}”`,source_ids:s?[s.id]:[],partner_allowed:true});setTab('notes')}}><NotebookPen size={12}/>引用到笔记</button>}</div></div>)}{!state.messages.some(m=>m.actor_id===actor)&&<p className="empty-small">你的第一句询问，会从这里开始。</p>}</div></div>
  <details className="investigation-log"><summary>调查行动记录 · {state.journal.length}</summary>{state.journal.slice().reverse().map((j,i)=><div className="timeline-item" key={i}><small>{formatDate(j.time)}</small>{j.text}</div>)}</details>
  </section><aside className="investigation-side"><div className="tab-bar">{[['scene','现场'],['evidence','证物'],['notes','笔记'],['partner','搭档']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{id==='evidence'?<FlaskConical size={16}/>:id==='notes'?<NotebookPen size={16}/>:id==='partner'?<BrainCircuit size={16}/>:<FileText size={16}/>}<span>{label}</span></button>)}</div>
  {tab==='scene'&&<div className="side-panel scene-brief"><div className="brief-quote">“每一个人都在说真话的一部分。”</div><div className="brief-list"><span><strong>{state.evidence.length}</strong>已发现证物</span><span><strong>{state.analyzed.length}</strong>已完成分析</span><span><strong>{state.characters.length}</strong>可询问角色</span></div><div className="side-tip"><Lightbulb size={16}/><div><b>调查提示</b><p>先搜索现场，再分析证物。把分析过的证物出示给相关人物，关键证词往往会随之改变。</p></div></div></div>}
  {tab==='evidence'&&<EvidencePanel state={state} action={action} addNote={addNote} busy={blocked}/>}
  <div hidden={tab!=='notes'}><NotesPanel state={state} user={user} refresh={refresh} notice={notice} incoming={incoming}/></div>
  {tab==='partner'&&<div className="side-panel partner-panel"><div className="partner-intro"><div className="partner-orb"><BrainCircuit size={25}/></div><div><span className="section-kicker">YOUR PARTNER / 推理搭档</span><h3>林砚 · {state.config.partner_style}</h3><p>只读取已发现证物和授权笔记。</p></div></div><div className="help-level"><span>帮助程度</span><div>{[1,2,3,4].map(n=><button key={n} className={n<=level?'active':''} aria-label={`帮助等级 ${n}`} onClick={()=>setLevel(n)}>{n}</button>)}</div><small>{['轻度提示','关键问题','多方案核对','完整证据梳理'][level-1]} · 已用 {state.hint_spent}/40 点</small></div><button className="partner-ask" disabled={blocked||!online} onClick={partner}><Sparkles size={15}/>请求一次分析 <span>{level} 点</span></button>{state.partner_analyses.slice().reverse().map(a=><div className="analysis-card" key={a.id}><small>{a.title}</small><p style={{whiteSpace:'pre-line'}}>{a.text}</p><div>{a.citations.map((c:string)=><span key={c}>来源：{state.evidence.find(e=>e.id===c)?.title||state.statements.find(s=>s.id===c)?.actor_name||'授权笔记'}</span>)}</div></div>)}</div>}
  </aside></div>{!closed&&<button className="settle-button" disabled={blocked||!online} onClick={()=>setSettle(true)}><Target size={16}/>提交结案</button>}
 </div>
}
