import { useState } from 'react'
import { Download, FileCheck, FlaskConical, Minus, Play, Plus, Save, Sparkles, Target, Upload, Users } from 'lucide-react'
import { api, download, type User } from './api'
import { useAuthorDraft } from './useAuthorDraft'
import { resizeCharacters as changeCharacters, resizeEvidence as changeEvidence } from './editorStructure'

export default function Editor({user,ensureUser,notice,start}:{user:User|null;ensureUser:()=>Promise<User>;notice:(x:string)=>void;start:(id:string)=>void}){
 const [issues,setIssues]=useState<any[]>([])
 const [valid,setValid]=useState(false),[busy,setBusy]=useState(false),[suggestion,setSuggestion]=useState<any>(null),[setting,setSetting]=useState('雨夜中一家即将闭馆的美术馆'),[tab,setTab]=useState('info')
 const draft=useAuthorDraft(user?.id,notice)
 const {content,raw,selected,drafts,saveStatus,loadList,setRaw,applied,save}=draft
 const setPackage=(data:any)=>{draft.setPackage(data);setValid(false);setIssues([])}
 const applyContent=(data:any)=>{draft.applyContent(data);setValid(false);setIssues([])}
 const initialize=async()=>{try{await ensureUser()}catch(e:any){notice(e.message)}}
 const update=(field:string,value:any)=>applyContent({...content,[field]:value})
 const resizeCharacters=(delta:number)=>{try{applyContent(changeCharacters(content,delta))}catch(e:any){notice(e.message)}}
 const resizeEvidence=(delta:number)=>{try{applyContent(changeEvidence(content,delta))}catch(e:any){notice(e.message)}}
 const parseRaw=()=>{try{applied();setValid(false);setIssues([]);notice('结构化内容已应用。请重新运行质检。')}catch(e:any){notice(e.message)}}
 const validate=async()=>{setBusy(true);try{const d=await api('/api/v1/author/validate',{method:'POST',body:JSON.stringify({content:applied()})});setIssues(d.issues);setValid(d.valid);notice(d.valid?'结构质检通过。启用前仍需试玩验证故事逻辑。':'请根据右侧报告修复阻断问题。')}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const saveClick=async()=>{setBusy(true);try{await save();notice('已保存为新的私人草稿版本。')}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const freezePlay=async()=>{if(!valid)return;setBusy(true);try{const id=await save();const result=await api(`/api/v1/author/drafts/${id}/freeze`,{method:'POST'});await draft.loadDraft(id);await loadList();start(result.script_id)}catch(e:any){notice(e.message);if(e.details?.issues)setIssues(e.details.issues)}finally{setBusy(false)}}
 const loadDraft=async(id:string)=>{setBusy(true);try{await draft.loadDraft(id);setValid(false);setIssues([])}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const generate=async()=>{setBusy(true);try{const d=await api('/api/v1/author/ideas',{method:'POST',body:JSON.stringify({title:content.title||'新案件',setting})});setSuggestion(d.suggestion);notice(d.provider==='mock'?'已生成模板建议，确认后可替换开场文字。':'AI 开场建议已生成，确认后可应用。')}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const importFile=async(file?:File)=>{if(!file)return;if(file.size>1_000_000){notice('仅支持 1 MB 以内的 JSON 内容包。');return}try{const value=JSON.parse(await file.text());if(!value.title||!value.schema_version)throw new Error();setPackage(value);notice('已载入内容包，请运行质检。')}catch{notice('导入失败，请选择符合内容协议的 JSON 文件。')}}
 if(!user)return <div className="page empty-state"><h2>开启你的私人工作台</h2><p>创建档案后，即可编辑教学案件、导入内容包、校验并测试游玩。</p><button className="primary-button" onClick={initialize}>建立档案并进入</button></div>
 if(!content)return <div className="empty-state">正在载入教学案件…</div>
 return <div className="page editor-page"><div className="editor-head"><div><span className="section-kicker">PRIVATE STUDIO / 私人创作</span><h1>剧本工作台</h1><p>从一个完整教学案件开始。基础表单用于编辑开场，结构编辑器可配置角色、证物、条件与答案。</p></div><span className="draft-badge"><span/>草稿保存状态见下方</span></div><div className="private-drafts"><div><span className="section-kicker">PRIVATE DRAFTS / 私人草稿</span><b>{drafts.length?`已保存 ${drafts.length} 个版本`:'还没有服务器草稿'}</b><small>{saveStatus}</small></div><div className="private-draft-list">{drafts.slice(0,6).map(d=><button disabled={busy} key={d.id} className={selected===d.id?'active':''} onClick={()=>loadDraft(d.id)}><strong>{d.title}</strong><span>V{d.version} · {d.status==='frozen'?'已冻结':'草稿'}</span></button>)}</div></div><div className="editor-tools"><select disabled={busy} aria-label="打开已存版本" value={selected} onChange={e=>loadDraft(e.target.value)}><option value="">打开已存版本…</option>{drafts.map(d=><option key={d.id} value={d.id}>{d.title} · V{d.version} · {d.status==='frozen'?'已冻结':'草稿'}</option>)}</select><button className="text-button" onClick={()=>{try{download((content.id||'case')+'.json',applied())}catch{const blob=new Blob([raw],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='unfinished-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}}><Download size={15}/>导出</button><label className="text-button file-upload"><Upload size={15}/>导入<input type="file" accept=".json,application/json" onChange={e=>importFile(e.target.files?.[0])}/></label></div>
 <div className="editor-layout"><fieldset disabled={busy} className="editor-canvas" style={{minWidth:0,margin:0}}><div className="canvas-toolbar"><div className="compact-actions"><button className={tab==='info'?'active':''} onClick={()=>{try{applied();setTab('info')}catch(e:any){notice(e.message)}}}>基础信息</button><button className={tab==='json'?'active':''} onClick={()=>setTab('json')}>完整结构</button></div><button disabled={busy} onClick={validate}><FileCheck size={15}/>运行质检</button></div>
 {tab==='info'?<><label>剧本标题<input value={content.title||''} maxLength={60} onChange={e=>update('title',e.target.value)}/></label><label>案件简介<textarea value={content.description||''} onChange={e=>update('description',e.target.value)} maxLength={1200}/></label><label>开场导入<textarea value={content.intro||''} onChange={e=>update('intro',e.target.value)} maxLength={2000}/></label><div className="editor-cards"><div><span className="editor-card-icon"><Users size={18}/></span><b>人物</b><small>{content.characters?.length||0} 位角色</small></div><div><span className="editor-card-icon"><FlaskConical size={18}/></span><b>证物</b><small>{content.evidence?.length||0} 件证物</small></div><div><span className="editor-card-icon"><Target size={18}/></span><b>结案</b><small>{content.questions?.length||0} 项判断</small></div></div><div className="structure-controls"><div><span><Users size={14}/>人物数量</span><button aria-label="减少人物" onClick={()=>resizeCharacters(-1)}><Minus size={13}/></button><b>{content.characters?.length||0}</b><button aria-label="增加人物" onClick={()=>resizeCharacters(1)}><Plus size={13}/></button></div><div><span><FlaskConical size={14}/>证物数量</span><button aria-label="减少证物" onClick={()=>resizeEvidence(-1)}><Minus size={13}/></button><b>{content.evidence?.length||0}</b><button aria-label="增加证物" onClick={()=>resizeEvidence(1)}><Plus size={13}/></button></div><p>新增条目会创建可继续编辑的占位内容；人物、证物的详细台词和条件请在“完整结构”中修改。</p></div></>:<><p className="editor-description">此处包含作者自己的完整答案。修改 JSON 后点击应用，再质检与保存。ID 引用、条件、线索可达性都会校验。</p><textarea className="editor-json" aria-label="剧本 JSON" spellCheck={false} value={raw} onChange={e=>{setRaw(e.target.value);setValid(false)}}/><button className="small-action editor-apply" onClick={parseRaw}>应用 JSON 修改</button></>}
 <div className="editor-actions"><button className="primary-button" disabled={busy} onClick={saveClick}><Save size={15}/>保存新版本</button><button className="small-action" disabled={!valid||busy} onClick={freezePlay}><Play size={14}/>冻结并试玩</button></div></fieldset>
 <aside className="editor-side"><div className="side-panel"><div className="panel-head"><span>{user.preferences.provider==='mock'?'开场模板助手':'AI 开场助手'}</span><Sparkles size={15}/></div><p>只生成开场文案建议。角色、证据与答案由作者在完整结构中编辑。</p><textarea aria-label="创作设定" value={setting} onChange={e=>setSetting(e.target.value)} maxLength={600}/><button className="small-action" disabled={busy||setting.length<5} onClick={generate}><Sparkles size={14}/>生成开场建议</button>{suggestion&&<div className="idea-preview"><h4>{suggestion.title}</h4><p>{suggestion.description}</p><p>{suggestion.intro}</p><button disabled={busy} className="small-action" onClick={()=>{try{applyContent({...applied(),...suggestion});setSuggestion(null)}catch(e:any){notice(e.message);return};notice('建议已应用到草稿，尚未冻结。')}}>接受并替换开场</button><button className="text-button" onClick={()=>setSuggestion(null)}>丢弃建议</button></div>}</div><div className="quality-card"><span className="section-kicker">QUALITY GATE</span><h3>{valid?'结构质检通过':'发布前质检'}</h3><div className="quality-row"><span className="quality-number">{issues.filter(x=>x.severity==='blocker').length}</span><span>阻断问题</span></div>{issues.map((x,i)=><div className={`quality-issue ${x.severity}`} key={i}><b>{x.path} · </b>{x.message}</div>)}{!issues.length&&<p>修改内容后运行质检，确认引用与关键线索可达。冻结版本不会覆盖进行中的存档。</p>}</div></aside></div></div>
}

