import { useEffect, useState } from 'react'
import { Download, LockKeyhole, ShieldCheck, Trash2 } from 'lucide-react'
import { api, download, type User } from './api'

export default function SettingsPage({user,updateUser,ensureUser,onAuthenticated,onDeleted,notice}:{user:User|null;updateUser:(u:User|null)=>void;ensureUser:()=>Promise<User>;onAuthenticated:(u:User)=>Promise<void>;onDeleted:()=>Promise<void>;notice:(x:string)=>void}){
 const [nickname,setNickname]=useState(user?.nickname||'见习侦探'),[provider,setProvider]=useState(user?.preferences?.provider||'mock'),[fontSize,setFontSize]=useState(user?.preferences?.font_size||'normal')
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'register'>(user?.guest?'register':'login'),[info,setInfo]=useState<any>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{if(user){setNickname(user.nickname);setProvider(user.preferences.provider||'mock');setFontSize(user.preferences.font_size||'normal');api('/api/v1/providers').then(setInfo).catch(e=>notice(e.message))}},[user,notice])
 const save=async()=>{setBusy(true);try{const d=await api('/api/v1/me/preferences',{method:'PATCH',body:JSON.stringify({nickname,provider,theme:'dark',font_size:fontSize})});updateUser(d.user);notice('偏好已保存。下一次角色对话将使用所选模式。')}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const auth=async()=>{setBusy(true);try{const d=await api(mode==='login'?'/api/v1/auth/login':'/api/v1/auth/register',{method:'POST',body:JSON.stringify({username,password})});setPassword('');await onAuthenticated(d.user);notice(mode==='register'?'账号已建立，原游客调查记录已保留。':'登录成功，可在总览查看已有存档。')}catch(e:any){notice(e.message)}finally{setBusy(false)}}
 const exportData=async()=>{try{download('casebook-player-export.json',await api('/api/v1/privacy/export'));notice('存档已导出，只包含你有权查看的内容。')}catch(e:any){notice(e.message)}}
 const remove=async()=>{if(!confirm('删除当前账号的全部存档、笔记和私人剧本？此操作无法撤销。'))return;try{await api('/api/v1/privacy/account',{method:'DELETE'});await onDeleted();notice('当前账号的数据已删除。')}catch(e:any){notice(e.message)}}
 return <div className="page settings-page"><div className="settings-head"><span className="section-kicker">CONTROL ROOM / 账户设置</span><h1>调查偏好</h1><p>你可以随时切换角色回答模式。真相、证物和结算始终由规则引擎控制。</p></div>
 {(!user||user.guest)&&<div className="settings-card account-card"><h3>{mode==='login'?'登录已有账号':'注册并保留当前调查'}</h3><p>{user?.guest?'注册会直接升级当前游客身份，已有存档继续保留。':'账号用于在同一服务器的不同设备间继续调查。'}</p><form className="auth-form" onSubmit={e=>{e.preventDefault();auth()}}><input aria-label="账号用户名" autoComplete="username" placeholder="用户名（3—32 位字母数字）" value={username} pattern="[a-zA-Z0-9_]{3,32}" required onChange={e=>setUsername(e.target.value)}/><input aria-label="账号密码" type="password" autoComplete={mode==='login'?'current-password':'new-password'} placeholder="密码（至少 8 位）" minLength={8} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary-button" disabled={busy} type="submit">{mode==='login'?'登录':'注册账号'}</button></form><button className="text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'没有账号？注册':'已有账号？登录'}</button>{!user&&<button className="ghost-button" onClick={()=>ensureUser().then(()=>notice('游客档案已建立')).catch(e=>notice(e.message))}>先以游客试玩</button>}</div>}
 {user&&<><div className="settings-card"><div className="settings-row"><div><b>调查员称呼</b><small>{user.guest?'游客档案':`账号：${user.username}`}</small></div><input aria-label="调查员称呼" value={nickname} maxLength={30} onChange={e=>setNickname(e.target.value)}/></div><div className="settings-row"><div><b>角色回答模式</b><small>模型从已授权的证词中选择回应，避免编造案件事实</small></div><select aria-label="角色回答模式" value={provider} onChange={e=>setProvider(e.target.value)}>{(info?.items||[{id:'mock',label:'本地演示',configured:true}]).map((p:any)=><option key={p.id} value={p.id} disabled={!p.configured}>{p.label} · {p.configured?'可用':'未配置'}</option>)}</select></div><div className="settings-row"><div><b>阅读字号</b><small>放大对话、场景、证物和笔记正文</small></div><select aria-label="阅读字号" value={fontSize} onChange={e=>setFontSize(e.target.value)}><option value="normal">标准</option><option value="large">大字</option></select></div><div className="settings-row"><div><b>今日模型用量</b><small>服务端设定调用上限；未配置价格时不显示金额估算</small></div><span className="privacy-ok">{info?.calls_today||0}/{info?.daily_limit||100} 次 · {info?.tokens_today||0} tokens</span></div><button className="primary-button" disabled={busy||!nickname.trim()} onClick={save}>保存偏好</button></div><div className="settings-card security-actions"><button className="ghost-button" onClick={exportData}><Download size={15}/>导出我的存档</button><button className="danger-button" onClick={remove}><Trash2 size={15}/>删除账户与存档</button></div></>}
 <div className="settings-note"><LockKeyhole size={17}/><div><b>模型与数据</b><p>本地演示根据已编写证词回应，不调用外部服务。使用 DeepSeek 或 OpenAI 时，本轮问题、当前角色资料与获准证词会发送给所选提供方；完整剧本答案、其他角色私密内容和未授权笔记不会发送。密钥仅由后端环境变量读取。</p></div></div>
 </div>
}
