import { useState } from 'react'
import { ArrowLeft, Target } from 'lucide-react'
import { command, type GameState } from './api'

export default function Submission({state,setState,back,notice,onFinished}:{state:GameState;setState:(s:GameState)=>void;back:()=>void;notice:(x:string)=>void;onFinished:()=>Promise<void>}){
 const [answers,setAnswers]=useState<Record<string,string>>({}),[evidence,setEvidence]=useState<string[]>([]),[report,setReport]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async()=>{setError('');if(state.questions.some(q=>!answers[q.id])){setError('请完成全部七项判断。');return}if(!confirmed){setError('请确认你已准备好结束本局调查。');return}setBusy(true);try{const data=await command(`/api/v1/sessions/${state.id}/submissions`,{expected_version:state.version,answers,evidence_ids:evidence,report});setState(data.state);await onFinished();notice('结案已归档，真相复盘已解锁。')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="page submission"><button className="text-button" onClick={back}><ArrowLeft size={15}/>返回调查</button><span className="section-kicker">FINAL DEDUCTION / 最终推理</span><h1>让证据说出答案。</h1><p>提交后，本局调查结束，评分与真相将一并揭示。自由报告用于保存你的推理过程，正式分数依据固定选项与证据覆盖计算。</p><form onSubmit={e=>{e.preventDefault();submit()}}><div className="submission-box form-grid">{state.questions.map(q=><label key={q.id}>{q.label}<select aria-label={q.label} required value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}><option value="" disabled>请选择你的判断</option>{q.options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}</div><div className="submission-box"><h3>支持判断的关键证物</h3><p className="empty-small">只有本局已发现的证物可以提交。不确定时，可以返回现场继续调查。</p><div className="check-list">{state.evidence.map(e=><label key={e.id}><input type="checkbox" checked={evidence.includes(e.id)} onChange={()=>setEvidence(v=>v.includes(e.id)?v.filter(id=>id!==e.id):[...v,e.id])}/>{e.title}</label>)}</div><textarea aria-label="自由推理报告" value={report} onChange={e=>setReport(e.target.value)} maxLength={8000} placeholder="你的推理报告（选填）：请解释证据之间的联系。"/></div><label className="confirm-row"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已准备好结束调查并揭示真相。</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="submission-actions"><button type="submit" className="primary-button" disabled={busy}>{busy?'正在归档…':'确认结案'}<Target size={16}/></button><button type="button" className="ghost-button" onClick={back}>继续收集证据</button></div></form></div>
}
